import React, { useState } from 'react';
import { Modal } from './Modal';
import { Button } from './Button';
import { Download, FileText, CheckCircle2 } from 'lucide-react';

export const DocumentPreviewModal = ({ isOpen, onClose, documentTitle }) => {
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadComplete, setDownloadComplete] = useState(false);

  const handleDownload = () => {
    setIsDownloading(true);
    // Simulate download delay
    setTimeout(() => {
      setIsDownloading(false);
      setDownloadComplete(true);
      
      // Reset after a few seconds
      setTimeout(() => {
        setDownloadComplete(false);
      }, 3000);
    }, 1500);
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Document Preview" maxWidth="800px">
      <div style={{ display: 'flex', flexDirection: 'column', height: '600px', backgroundColor: 'var(--color-background)', margin: '-1.5rem', borderBottomLeftRadius: '0.5rem', borderBottomRightRadius: '0.5rem', overflow: 'hidden' }}>
        
        {/* Toolbar */}
        <div style={{ padding: '1rem 1.5rem', backgroundColor: 'var(--color-surface)', borderBottom: '1px solid var(--color-border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <div style={{ padding: '0.5rem', backgroundColor: 'rgba(59, 130, 246, 0.1)', borderRadius: '0.5rem', color: '#3B82F6' }}>
              <FileText size={20} />
            </div>
            <div>
              <h3 style={{ fontSize: '1rem', fontWeight: 600 }}>{documentTitle || 'Draft Document'}</h3>
              <p className="text-muted" style={{ fontSize: '0.75rem' }}>Generated by DocuEase AI</p>
            </div>
          </div>
          
          <Button 
            onClick={handleDownload} 
            disabled={isDownloading || downloadComplete}
            style={{ 
              display: 'flex', alignItems: 'center', gap: '0.5rem',
              backgroundColor: downloadComplete ? '#10B981' : 'var(--color-primary)'
            }}
          >
            {downloadComplete ? (
              <><CheckCircle2 size={16} /> Downloaded</>
            ) : isDownloading ? (
              'Preparing...'
            ) : (
              <><Download size={16} /> Download PDF</>
            )}
          </Button>
        </div>

        {/* Document Viewer (A4 format simulation) */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '2rem', display: 'flex', justifyContent: 'center', backgroundColor: '#F3F4F6' }}>
          <div style={{ 
            width: '100%', 
            maxWidth: '21cm', /* A4 width */
            minHeight: '29.7cm', /* A4 height */
            backgroundColor: 'white', 
            boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
            padding: '4cm 3cm', /* standard margins */
            color: '#374151'
          }}>
            <h1 style={{ fontSize: '1.5rem', fontWeight: 700, textAlign: 'center', marginBottom: '2rem', textTransform: 'uppercase' }}>
              {documentTitle}
            </h1>
            
            <p style={{ marginBottom: '1.5rem', textAlign: 'right' }}>
              Date: {new Date().toLocaleDateString('en-IN')}
            </p>

            <h3 style={{ fontSize: '1.125rem', fontWeight: 600, marginBottom: '1rem' }}>Applicant Details</h3>
            <div style={{ display: 'grid', gridTemplateColumns: '150px 1fr', gap: '0.5rem', marginBottom: '2rem', border: '1px solid #E5E7EB', padding: '1rem' }}>
              <strong style={{ color: '#6B7280' }}>Business Name:</strong> <span>Optixi Media</span>
              <strong style={{ color: '#6B7280' }}>Address:</strong> <span>123 Tech Park, India</span>
              <strong style={{ color: '#6B7280' }}>Entity Type:</strong> <span>Private Limited</span>
            </div>

            <h3 style={{ fontSize: '1.125rem', fontWeight: 600, marginBottom: '1rem' }}>Declaration</h3>
            <p style={{ lineHeight: 1.8, marginBottom: '1.5rem', textAlign: 'justify' }}>
              This document serves as a draft application for <strong>{documentTitle}</strong>. 
              All information provided herein is true and correct to the best of my knowledge and belief. 
              I understand that any false statement or misrepresentation may result in the rejection of this application.
            </p>
            <p style={{ lineHeight: 1.8, marginBottom: '3rem', textAlign: 'justify' }}>
              This draft was automatically generated by DocuEase AI. It is recommended to have this reviewed by a qualified professional before final submission to the respective government portal.
            </p>

            <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '4rem' }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ width: '150px', borderBottom: '1px solid #9CA3AF', height: '40px' }} />
                <p style={{ fontSize: '0.875rem', marginTop: '0.5rem' }}>Authorized Signatory</p>
              </div>
              <div style={{ textAlign: 'center' }}>
                <div style={{ width: '150px', borderBottom: '1px solid #9CA3AF', height: '40px' }} />
                <p style={{ fontSize: '0.875rem', marginTop: '0.5rem' }}>Professional Stamp</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Modal>
  );
};
